### ISSUE TITLE
Operations on Merged Variables (w)

### ISSUE THREAD

**Issue by emely-pi** [lucfra/RFHO#1]
Hi,
for an university project I'm using your code and trying to recreate the experiment in the file mint_deep_ho.py. I've changed the optimizer to Gradient Descent and now want to add very small numbers to w during gradient descent. Unfortunately, I always get back the error: ValueError: None values not supported. I've checked and saw that it is a Merged Variable with functions to access it but I have been so far unable to do so. 
How can I access the weights w to add a very small number before the function grad = tf.gradients(loss, #MergedVariable.get_tensor(w), w)[0] is called?

Thanks in advance!

**Comment by lucfra** [comment]
Ciao Emely, 

I no longer support this package. I've written a new package https://github.com/lucfra/FAR-HO which implements the same algorithms (and a little more) but should be much easier to use (in particular there are no more  `MergedVariable`s).
Please, send me a private mail at luca.franceschi@iit.it or start a new issue on FAR-HO (I believe also an other colleague of yours wrote to me a similar mail).

Cheers, 
Luca
